server:
  port: 8000
  servlet:
    context-path: /api/
  error:
    include-message: always
    include-stacktrace: never

spring:
  profiles:
    active: prod
  security:
    user:
      name: doesntmatter
      password: doesntmatter

  flyway:
    baseline-on-migrate: true

  datasource:
    url: jdbc:mysql://mysqldb:3306/expzendb?useSSL=false&allowPublicKeyRetrieval=true
    username: nikhilcodes
    password: testtreasure321
# -Dspring.profiles.active=dev
jwt:
  secret: gf768oyut7867v58b7rybpolkl09t6266g
